// 节点间 gRPC 通信的接口定义
//
// 这个文件是"接口蓝图"——声明了：
//   - 消息长什么样（message）
//   - 提供哪些远程方法（service + rpc）
//
// 为什么用 protobuf 而不是 JSON？
//   - 体积小：二进制编码，比 JSON 文本小得多（尤其是值很大的时候）
//   - 快：无需解析文本，直接二进制序列化
//   - 强类型：.proto 文件就是跨语言契约
//
// 编译命令（生成 cachepb.pb.go）：
//   protoc --proto_path=pkg/cachepb --go_out=pkg/cachepb \
//          --go_opt=paths=source_relative pkg/cachepb/cachepb.proto
//
// 用 protoc 生成 Go 代码后，客户端/服务端都有现成的骨架。
//
// syntax	关键字：声明用哪个语法版本

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: grpcpeer/grpcpeer.proto

//proto的包名

package grpcpeer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GroupCache_Get_FullMethodName        = "/grpcpeer.GroupCache/Get"
	GroupCache_Invalidate_FullMethodName = "/grpcpeer.GroupCache/Invalidate"
)

// GroupCacheClient is the client API for GroupCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 缓存服务：节点之间调用的方法都声明在这里。
// service：声明一个 RPC 服务（一组远程方法的集合）,名字是GroupCache
// rpc: 声明一个远程方法
// 注意消息用了 cachepb.Request / cachepb.Response（跨包引用，要带包名前缀）。
// 一个service对应一个客户端桩,通常一个proto文件一个service
type GroupCacheClient interface {
	// 定义一个远程方法 Get，传入 Request，返回 Response
	Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Invalidate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Invalidation, Ack], error)
}

type groupCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupCacheClient(cc grpc.ClientConnInterface) GroupCacheClient {
	return &groupCacheClient{cc}
}

func (c *groupCacheClient) Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, GroupCache_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupCacheClient) Invalidate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Invalidation, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GroupCache_ServiceDesc.Streams[0], GroupCache_Invalidate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Invalidation, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GroupCache_InvalidateClient = grpc.BidiStreamingClient[Invalidation, Ack]

// GroupCacheServer is the server API for GroupCache service.
// All implementations must embed UnimplementedGroupCacheServer
// for forward compatibility.
//
// 缓存服务：节点之间调用的方法都声明在这里。
// service：声明一个 RPC 服务（一组远程方法的集合）,名字是GroupCache
// rpc: 声明一个远程方法
// 注意消息用了 cachepb.Request / cachepb.Response（跨包引用，要带包名前缀）。
// 一个service对应一个客户端桩,通常一个proto文件一个service
type GroupCacheServer interface {
	// 定义一个远程方法 Get，传入 Request，返回 Response
	Get(context.Context, *Request) (*Response, error)
	Invalidate(grpc.BidiStreamingServer[Invalidation, Ack]) error
	mustEmbedUnimplementedGroupCacheServer()
}

// UnimplementedGroupCacheServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGroupCacheServer struct{}

func (UnimplementedGroupCacheServer) Get(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGroupCacheServer) Invalidate(grpc.BidiStreamingServer[Invalidation, Ack]) error {
	return status.Error(codes.Unimplemented, "method Invalidate not implemented")
}
func (UnimplementedGroupCacheServer) mustEmbedUnimplementedGroupCacheServer() {}
func (UnimplementedGroupCacheServer) testEmbeddedByValue()                    {}

// UnsafeGroupCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupCacheServer will
// result in compilation errors.
type UnsafeGroupCacheServer interface {
	mustEmbedUnimplementedGroupCacheServer()
}

func RegisterGroupCacheServer(s grpc.ServiceRegistrar, srv GroupCacheServer) {
	// If the following call panics, it indicates UnimplementedGroupCacheServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GroupCache_ServiceDesc, srv)
}

func _GroupCache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupCache_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupCacheServer).Get(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupCache_Invalidate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GroupCacheServer).Invalidate(&grpc.GenericServerStream[Invalidation, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GroupCache_InvalidateServer = grpc.BidiStreamingServer[Invalidation, Ack]

// GroupCache_ServiceDesc is the grpc.ServiceDesc for GroupCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroupCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcpeer.GroupCache",
	HandlerType: (*GroupCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _GroupCache_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Invalidate",
			Handler:       _GroupCache_Invalidate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpcpeer/grpcpeer.proto",
}
