// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: grpcpeer/grpcpeer.proto

//proto的包名

package grpcpeer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// message	：定义一个"消息"（相当于 Go 的 struct）
// 字段完整格式：类型 字段名 = 字段编号;
// Request 一个缓存查询请求：在哪个组、查哪个 key。
// proto 字段名约定小写下划线（group_name），生成的 Go 代码会自动转成驼峰 GroupName
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"` // 组名（如 scores）
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`     // 要查的 key（如 Tom）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_grpcpeer_grpcpeer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpcpeer_grpcpeer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_grpcpeer_grpcpeer_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Request) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// bytes 对应go中 []byte	裸字节（图片/音频/序列化数据）
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_grpcpeer_grpcpeer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpcpeer_grpcpeer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_grpcpeer_grpcpeer_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// 失效通知：告诉别的节点"这个 key 别缓存了"
type Invalidation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invalidation) Reset() {
	*x = Invalidation{}
	mi := &file_grpcpeer_grpcpeer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invalidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invalidation) ProtoMessage() {}

func (x *Invalidation) ProtoReflect() protoreflect.Message {
	mi := &file_grpcpeer_grpcpeer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invalidation.ProtoReflect.Descriptor instead.
func (*Invalidation) Descriptor() ([]byte, []int) {
	return file_grpcpeer_grpcpeer_proto_rawDescGZIP(), []int{2}
}

func (x *Invalidation) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Invalidation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// 确认通知
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_grpcpeer_grpcpeer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_grpcpeer_grpcpeer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_grpcpeer_grpcpeer_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Ack) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_grpcpeer_grpcpeer_proto protoreflect.FileDescriptor

const file_grpcpeer_grpcpeer_proto_rawDesc = "" +
	"\n" +
	"\x17grpcpeer/grpcpeer.proto\x12\bgrpcpeer\"1\n" +
	"\aRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\" \n" +
	"\bResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"6\n" +
	"\fInvalidation\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"-\n" +
	"\x03Ack\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key2s\n" +
	"\n" +
	"GroupCache\x12,\n" +
	"\x03Get\x12\x11.grpcpeer.Request\x1a\x12.grpcpeer.Response\x127\n" +
	"\n" +
	"Invalidate\x12\x16.grpcpeer.Invalidation\x1a\r.grpcpeer.Ack(\x010\x01B\x1dZ\x1bdistcache/grpcpeer;grpcpeerb\x06proto3"

var (
	file_grpcpeer_grpcpeer_proto_rawDescOnce sync.Once
	file_grpcpeer_grpcpeer_proto_rawDescData []byte
)

func file_grpcpeer_grpcpeer_proto_rawDescGZIP() []byte {
	file_grpcpeer_grpcpeer_proto_rawDescOnce.Do(func() {
		file_grpcpeer_grpcpeer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcpeer_grpcpeer_proto_rawDesc), len(file_grpcpeer_grpcpeer_proto_rawDesc)))
	})
	return file_grpcpeer_grpcpeer_proto_rawDescData
}

var file_grpcpeer_grpcpeer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpcpeer_grpcpeer_proto_goTypes = []any{
	(*Request)(nil),      // 0: grpcpeer.Request
	(*Response)(nil),     // 1: grpcpeer.Response
	(*Invalidation)(nil), // 2: grpcpeer.Invalidation
	(*Ack)(nil),          // 3: grpcpeer.Ack
}
var file_grpcpeer_grpcpeer_proto_depIdxs = []int32{
	0, // 0: grpcpeer.GroupCache.Get:input_type -> grpcpeer.Request
	2, // 1: grpcpeer.GroupCache.Invalidate:input_type -> grpcpeer.Invalidation
	1, // 2: grpcpeer.GroupCache.Get:output_type -> grpcpeer.Response
	3, // 3: grpcpeer.GroupCache.Invalidate:output_type -> grpcpeer.Ack
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcpeer_grpcpeer_proto_init() }
func file_grpcpeer_grpcpeer_proto_init() {
	if File_grpcpeer_grpcpeer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcpeer_grpcpeer_proto_rawDesc), len(file_grpcpeer_grpcpeer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcpeer_grpcpeer_proto_goTypes,
		DependencyIndexes: file_grpcpeer_grpcpeer_proto_depIdxs,
		MessageInfos:      file_grpcpeer_grpcpeer_proto_msgTypes,
	}.Build()
	File_grpcpeer_grpcpeer_proto = out.File
	file_grpcpeer_grpcpeer_proto_goTypes = nil
	file_grpcpeer_grpcpeer_proto_depIdxs = nil
}
